### ISSUE TITLE
Adding File Structure in README.md

### ISSUE THREAD

**Issue by Aman-Singh-Kushwaha** [semikolan-co/blog.semikolan.co#111]
Whenever I have to pick a file, I have to visit/search in each folder of a directory which makes it irritating to find the desired file to work on, and takes time.

If there would be **a file structure to guide us through**, it makes it easier to file and time saviour.

This would look something like this after completion
![image](https://user-images.githubusercontent.com/96011814/195167767-e4426b2e-1c90-465a-86ef-eea3a40f5bab.png)

**Comment by ankurg132** [comment]
Thanks for pointing this out, we should go for this!
