### ISSUE TITLE
Category user interface in editing/writing blogs

### ISSUE THREAD

**Issue by ankurg132** [semikolan-co/blog.semikolan.co#72]
The color of category selection text and background is same and hence I'm unable to select the correct category. Here is a screenshot of the same-
![image](https://user-images.githubusercontent.com/31045221/133260781-e619bcb6-6244-4778-8a20-2d10988366df.png)

**Comment by kirillarutyunov** [comment]
Can you assign this issue for me? I will help :–)

**Comment by meinhoonharsh** [comment]
@kirillarutyunov assigned to you

**Comment by kirillarutyunov** [comment]
@meinhoonharsh Can you check my PR, pls? :–)

**Comment by kirillarutyunov** [comment]
Don't forget to close this issue.

**Comment by ankurg132** [comment]
@meinhoonharsh if this looks good shall I close this issue?
