### ISSUE TITLE
Author name not showing in searching

### ISSUE THREAD

**Issue by ankurg132** [semikolan-co/blog.semikolan.co#79]
When we search in the website, you can't see the authors name which is not the issue in case of the homepage. 
Here is a screenshot of the bug-
![image](https://user-images.githubusercontent.com/31045221/135727668-2b262f10-b5be-4e9e-a135-0cba5254d171.png)

We should see the author's name similar to the homepage here also.

**Comment by Enorion** [comment]
Should be fixed by #80 - No promise though ;)
