### ISSUE TITLE
Add the discord link in readme.md

### ISSUE THREAD

**Issue by ankurg132** [semikolan-co/blog.semikolan.co#81]
There should be a discord link in the readme.md file to discord.semikolan.co with a little description that says "You can join the Semikolan Discord Server to have a discussion about the project or ask out about any other queries." or anything similar.

**Comment by meinhoonharsh** [comment]
It would be great if you add some content mentioning the need for joining the server
Like we can mention something like, If you want to Communicate with the Other Contributors on this Project, then do join https://discord.semikolan.co

**Comment by kfkonrad** [comment]
Can you assign me the issue please? I'll get to work in the mean time

**Comment by Harsh-bartariya** [comment]
I aslo want to work on this issue brother...can u pls assign it to me

**Comment by meinhoonharsh** [comment]
@kfkonrad @Harsh-bartariya We've assigned this Issue to both of you

**Comment by kfkonrad** [comment]
My PR is ready. Feel free to wait and choose whichever phrasing you like best. But please remember to label the PR that isn't getting merged with `hacktoberfest-accepted`
